services:
  postgres:
    image: postgres:16
    container_name: bantads-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bantads-net
    mem_limit: 384m
    command: ["postgres", "-c", "shared_buffers=128MB"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bantads"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: bantads-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bantads-net
    mem_limit: 384m
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bantads-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: